version: '3'
services:
  rabbitmq:
    image: rabbitmq:3.6-management
    environment:
      RABBITMQ_DEFAULT_USER: "bunnyrabbit"
      RABBITMQ_DEFAULT_PASS: "bunnypass"
    ports:
      - "5672:5672"
      - "15672:15672"
  db:
    image: postgres:10.0
    restart: always
    environment:
      POSTGRES_PASSWORD: secretpass
      POSTGRES_USER: secretuser
    ports:
      - "5432:5432"
  web:
    build: ./playground
    command: "bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"
    depends_on:
      - db
      - rabbitmq
    volumes:
      - ./playground:/playground
  prime_workstation:
    build: ./prime_workstation
    command: "bundle exec ruby worker.rb"
    depends_on:
      - rabbitmq
    volumes:
      - ./prime_workstation:/worker
